services:
  - type: web
    name: mahsr-t3-dpr
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: SUPABASE_URL
        value: https://eibmhrjjtdcbydijwmbn.supabase.co
      - key: SUPABASE_KEY
        scope: run
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpYm1ocmpqdGRjYnlkamp3bWJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0OTA0OTUsImV4cCI6MjA3ODA2NjQ5NX0.9B5d0sbHnFVbRd61NH-nP5KFokfNGsNvroUXYu7Wxps
